environment:
  global:
    PYTHON: "C:\\conda"
    CONDA_ENVIRONMENT: "environment2.yml"
    PIP_DEPENDENCIES: "codecov"
  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
cache:
  - "C:\\Users\\appveyor\\AppData\\Local\\pip\\"

install:
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "python setup.py develop"
  - "SET MNE_SKIP_NETWORK_TESTS=1"
  - "SET MNE_FORCE_SERIAL=true"  # otherwise joblib will bomb
  - "SET MNE_LOGGING_LEVEL=warning"
  - "python -c \"import mne; mne.datasets.testing.data_path()\""
  - "python -c \"import mne; print(mne.sys_info())\""

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests, but exclude ones that take a very long time
  - "py.test -m \"not ultraslowtest\" mne"

on_success:
  - "codecov"
