name: mne
channels:
- defaults
- conda-forge
- clinicalgraphics  # for vtk
dependencies:
- python=3.6
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt=4.11.4
- qt=4.8.7
- pandas
- scikit-learn
- jupyter
- ipython
- statsmodels
- h5py
- vtk
- pip:
  - mayavi
  - "git+https://github.com/nipy/PySurfer.git"
  - nibabel
  - nilearn
  - neo
  - pillow
  - nose
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_bootstrap_theme
  - numpydoc
  - sphinx-gallery
