name: mne
channels:
- menpo
- defaults
dependencies:
- python=3.5
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt=4
- mayavi
- pandas
- scikit-learn
- joblib
- jupyter
- statsmodels
- h5py
- sphinx
- nose
- pytest
- pytest-cov
- spyder
- pip:
  - mne
  - "git+git://github.com/enthought/pyface.git@13a064de48adda3c880350545717d8cf8929afad"
  - "git+git://github.com/enthought/traitsui.git@ee8ef0a34dfc1db18a8e2c0301cc18d96b7a3e2f"
  - "git+git://github.com/nipy/PySurfer.git"
  - nibabel
  - nilearn
  - neo
  - pillow
  - pytest-sugar
  - pytest-xdist
  - flake8
  - pydocstyle
  - sphinx-gallery
  - sphinx_bootstrap_theme
  - numpydoc
