name: mne27
channels:
- conda-forge
- defaults
dependencies:
- python=2.7
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt=4.11.4
- qt=4.8.7
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- traitlets=4.3.2=py27_0
- vtk=5.10.1=py27_0
- mayavi=4.4.0=np19py27_0
- pandas
- scikit-learn
- jupyter
- ipython
- statsmodels
- h5py
- sphinx
- vtk
- nose
- pytest
- spyder
- pip:
  - mne
  - "git+https://github.com/nipy/PySurfer.git"
  - nibabel
  - nilearn
  - neo
  - pillow
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - flake8
  - pydocstyle
  - sphinx_bootstrap_theme
  - numpydoc
  - sphinx-gallery
